### ISSUE TITLE
Map does not work in TripleA 1.9 prerelease

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_g40_balanced#1]
world_war_ii_g40_balanced.zip version 0.3 downloaded from https://github.com/triplea-maps/world_war_ii_g40_balanced/releases does not work using TripleA Prerelease 1.9.0.2700.

Installed in downloadedMaps it shows in the installed games list when hitting "Select Game" in TripleA.

But TripleA Console shows (only first lines and last issue copied here):

triplea.engine.version.bin:1.9
SAXParseException: game: World War II G40 Balanced, line: 1950, column: 20, error: Elementtyp "attatchmentList" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1952, column: 163, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1955, column: 170, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1958, column: 166, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1961, column: 170, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1965, column: 170, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1972, column: 168, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1976, column: 66, error: Content des Elementtyps "attatchment" muss "EMPTY" entsprechen. Untergeordnete Elemente mit dem Typ "comment" sind nicht zulässig.
SAXParseException: game: World War II G40 Balanced, line: 1979, column: 173, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1981, column: 66, error: Content des Elementtyps "attatchment" muss "EMPTY" entsprechen. Untergeordnete Elemente mit dem Typ "comment" sind nicht zulässig.
SAXParseException: game: World War II G40 Balanced, line: 1985, column: 174, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 1989, column: 176, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 2003, column: 10, error: Content des Elementtyps "attatchment" muss "EMPTY" entsprechen. Untergeordnete Elemente mit dem Typ "comment" sind nicht zulässig.
SAXParseException: game: World War II G40 Balanced, line: 2005, column: 178, error: Elementtyp "attatchment" muss deklariert werden.
SAXParseException: game: World War II G40 Balanced, line: 2009, column: 26, error: Content des Elementtyps "attatchmentList" muss "EMPTY" entsprechen. Untergeordnete Elemente mit dem Typ "comment" sind nicht zulässig.
SAXParseException: game: World War II G40 Balanced, line: 2010, column: 139, error: Elementtyp "attatchment" muss deklariert werden.
...
...
...
SAXParseException: game: World War II G40 Balanced, line: 15649, column: 8, error: Content des Elementtyps "game" muss "(info,loader,triplea?,diceSides?,map,resourceList?,playerList,unitList?,relationshipTypes?,territoryEffectList?,gamePlay,production?,technology?,attachmentList?,initialize?,propertyList?)" entsprechen.

The game/map cannot be selected then.

**Comment by DanVanAtta** [comment]
attatchment was never updated on this map, needs to be corrected to spell instead "attachment"

**Comment by panther2** [comment]
Is it only the game.xml that needs to be fixed - or are there other files involved?

**Comment by DanVanAtta** [comment]
- create a fork
- clone it 
- create a branch and make the update
- commit and push the branch
- head to the github-maps repository for the map, there should be a prompt asking you if you'd like to do a PR with the branch you just pushed

**Comment by simon33-2** [comment]
I also need help with that - how do I commit? For SVN I need a username and a password don't I? I'm getting an authentication failed message without even prompting for a password. Perhaps it validates on the username?

**Comment by panther2** [comment]
Thanks Dan, I will try that.

**Comment by panther2** [comment]
OK - I hope I have done everything correctly. Please let me know if something went wrong.
Thank you!

**Comment by DanVanAtta** [comment]
@simon33-2  - the readme here could help you get started: https://github.com/triplea-maps/Project
The wiki has some instructions, they are a bit dated, but still somewhat recent: https://github.com/triplea-maps/Project/wiki

To avoid hijacking this issue, please cut a new issue in the maps project: https://github.com/triplea-maps/Project/issues/new, or gitter for quicker, or more conversational questions: 
- https://gitter.im/triplea-maps
- https://gitter.im/triplea-game/social
