### ISSUE TITLE
Some UK_pacific facilities are owned by British...

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_g40_balanced#5]
.... that leads to UK_europe paying for damages on the Pacific side of the map instead of UK_pacific economy.
Issue is already fixed for world_war_ii_global.
Thanks to simon33-2 for identifying the reason.

Pull request to fix this issue soon to follow.

**Comment by simon33-2** [comment]
Hi @DanVanAtta ,
Please merge this issue also.
